vich_uploader:
    db_driver: orm

    mappings:
        bienimmo:
            uri_prefix: /assets/images/bienimmo
            upload_destination: '%kernel.project_dir%/public/assets/images/bienimmo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true
